'use client';

import { motion } from 'framer-motion';

interface ResultsScreenProps {
  sentences: string[];
  imageUrl: string;
}

export default function ResultsScreen({ sentences, imageUrl }: ResultsScreenProps) {
  return (
    <div className="min-h-screen bg-gray-950 flex items-center justify-center p-6">
      <div className="w-full max-w-6xl grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
        {/* Left side - Top 5 sentences */}
        <motion.div
          initial={{ x: -50, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          transition={{ delay: 0.3 }}
        >
          <h2 className="text-3xl font-bold text-white mb-2">Neural Network Output</h2>
          <p className="text-gray-400 mb-6">Top {sentences.length} sentences generated by the crowd</p>

          <div className="space-y-4">
            {sentences.map((sentence, index) => (
              <motion.div
                key={index}
                initial={{ x: -30, opacity: 0 }}
                animate={{ x: 0, opacity: 1 }}
                transition={{ delay: 0.5 + index * 0.2 }}
                className="relative"
              >
                <div className="flex items-start gap-4 p-4 bg-gray-800/60 rounded-xl border border-gray-700">
                  <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm ${
                    index === 0 ? 'bg-yellow-500 text-black' :
                    index === 1 ? 'bg-gray-300 text-black' :
                    index === 2 ? 'bg-amber-700 text-white' :
                    'bg-gray-600 text-gray-200'
                  }`}>
                    {index + 1}
                  </div>
                  <p className="text-gray-200 text-lg leading-relaxed capitalize">{sentence}</p>
                </div>
              </motion.div>
            ))}
          </div>

          {sentences.length === 0 && (
            <div className="text-center py-12 text-gray-500">
              <p className="text-xl">No sentences were generated</p>
              <p className="text-sm mt-2">Not enough players submitted responses</p>
            </div>
          )}
        </motion.div>

        {/* Right side - Original image */}
        <motion.div
          initial={{ x: 50, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          transition={{ delay: 0.5 }}
          className="flex flex-col items-center"
        >
          <h3 className="text-xl font-semibold text-gray-300 mb-4">Original Image</h3>
          <div className="rounded-2xl overflow-hidden border-2 border-cyan-500/30 shadow-2xl shadow-cyan-500/10 w-full max-w-md">
            <img
              src={imageUrl}
              alt="Original image"
              className="w-full h-80 object-cover"
            />
          </div>

          <motion.div
            className="mt-6 text-center"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
          >
            <p className="text-sm text-gray-500">
              The crowd processed this image through three neural network layers
            </p>
            <div className="flex items-center justify-center gap-4 mt-3">
              <span className="text-blue-400 text-xs">Input → Words</span>
              <span className="text-gray-600">→</span>
              <span className="text-purple-400 text-xs">Hidden → Phrases</span>
              <span className="text-gray-600">→</span>
              <span className="text-amber-400 text-xs">Output → Sentences</span>
            </div>
          </motion.div>
        </motion.div>
      </div>
    </div>
  );
}
